import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import { Injectable, PLATFORM_ID, inject } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

import { AppLanguage } from '../models/language.model';

const enTranslations = {
  'common.actions': 'Actions',
  'common.allStatuses': 'All statuses',
  'common.backToDashboard': 'Back to dashboard',
  'common.cancel': 'Cancel',
  'common.clear': 'Clear',
  'common.destination': 'Destination',
  'common.distance': 'Distance',
  'common.driver': 'Driver',
  'common.email': 'Email',
  'common.estimatedDuration': 'Estimated Duration',
  'common.loading': 'Loading...',
  'common.loadingData': 'Loading data...',
  'common.name': 'Name',
  'common.noActions': 'No actions',
  'common.notes': 'Notes',
  'common.of': 'of',
  'common.origin': 'Origin',
  'common.phone': 'Phone',
  'common.route': 'Route',
  'common.saving': 'Saving...',
  'common.search': 'Search',
  'common.showing': 'Showing',
  'common.status': 'Status',
  'common.vehicle': 'Vehicle',
  'common.view': 'View',
  'common.viewAll': 'View all',
  'common.viewOnly': 'View only',
  'empty.defaultMessage': 'There is no information to display yet.',
  'empty.defaultTitle': 'No records found',
  'sidebar.brand.subtitle': 'Control Panel',
  'sidebar.close': 'Close sidebar',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.vehicles': 'Vehicles',
  'sidebar.drivers': 'Drivers',
  'sidebar.routes': 'Routes',
  'sidebar.trips': 'Trips',
  'sidebar.admin': 'Admin',
  'sidebar.users': 'Users',
  'sidebar.settings': 'Settings',
  'sidebar.theme.light': 'Light mode',
  'sidebar.theme.dark': 'Dark mode',
  'sidebar.theme.switchToLight': 'Switch to light theme',
  'sidebar.theme.switchToDark': 'Switch to dark theme',
  'sidebar.meta.project': 'TransitOps Platform',
  'sidebar.meta.description': 'Angular Admin System',
  'settings.title': 'Settings',
  'settings.subtitle': 'Manage personal workspace preferences for TransitOps.',
    'settings.home.kicker': 'Workspace preferences',
  'settings.home.title': 'Choose what you want to configure',
  'settings.home.description':
    'Manage your account profile and interface language from focused sections designed to keep TransitOps simple and predictable.',
  'settings.home.profile.title': 'Profile',
  'settings.home.profile.description':
    'Update your personal information, avatar, email, phone and password security settings.',
  'settings.home.language.title': 'Language',
  'settings.home.language.description':
    'Choose the interface language used across navigation, settings and operational screens.',
  'settings.home.openSection': 'Open section',
  'settings.language.title': 'Language',
  'settings.language.description': 'Choose the display language for navigation and settings.',
  'settings.language.english': 'English',
  'settings.language.spanish': 'Spanish',
  'settings.language.current': 'Current language',

  'settings.account.kicker': 'Account center',
  'settings.account.profileFallbackTitle': 'Profile',
  'settings.account.fallbackDescription': 'Manage your personal information and security settings.',
  'settings.account.role': 'Role',
  'settings.account.status': 'Status',

  'settings.avatar.kicker': 'Avatar',
  'settings.avatar.title': 'Profile photo',
  'settings.avatar.description': 'Upload a JPEG, PNG or WebP image to personalize your account.',
  'settings.avatar.recommended':
    'Recommended: square image, maximum 2 MB. Allowed formats: JPEG, PNG and WebP.',
  'settings.avatar.upload': 'Upload photo',
  'settings.avatar.uploading': 'Uploading...',
  'settings.avatar.remove': 'Remove photo',
  'settings.avatar.removing': 'Removing...',
  'settings.avatar.success.update': 'Avatar updated successfully.',
  'settings.avatar.success.delete': 'Avatar deleted successfully.',
  'settings.avatar.error.invalidType': 'Avatar must be a JPEG, PNG, or WebP image.',
  'settings.avatar.error.tooLarge': 'Avatar file must not exceed 2 MB.',
  'settings.avatar.error.none': 'There is no avatar to delete.',
  'settings.avatar.error.update': 'Avatar could not be updated.',
  'settings.avatar.error.delete': 'Avatar could not be deleted.',

  'settings.profile.kicker': 'Profile',
  'settings.profile.title': 'Personal information',
  'settings.profile.description':
    'Update your name, email and phone number used across TransitOps.',
  'settings.profile.firstName': 'First name',
  'settings.profile.lastName': 'Last name',
  'settings.profile.email': 'Email',
  'settings.profile.phone': 'Phone',
  'settings.profile.currentPassword': 'Current password',
  'settings.profile.currentPasswordPlaceholder': 'Required only when changing email',
  'settings.profile.currentPasswordHint':
    'For security, email changes require your current password.',
  'settings.profile.validation.name': 'Name must contain between 2 and 60 characters.',
  'settings.profile.validation.email': 'Enter a valid email address.',
  'settings.profile.validation.phone': 'Phone must contain between 8 and 25 characters.',
  'settings.profile.saving': 'Saving...',
  'settings.profile.save': 'Save profile',
  'settings.profile.success': 'Profile updated successfully.',
  'settings.profile.error.noUser': 'There is no authenticated user loaded.',
  'settings.profile.error.emailPasswordRequired':
    'Current password is required when changing your email.',
  'settings.profile.error.update': 'Profile could not be updated.',

  'settings.password.kicker': 'Security',
  'settings.password.title': 'Password',
  'settings.password.description': 'Change your password using your current credentials.',
  'settings.password.current': 'Current password',
  'settings.password.new': 'New password',
  'settings.password.confirm': 'Confirm password',
  'settings.password.validation.current': 'Current password is required.',
  'settings.password.validation.new': 'Use at least 8 characters, including letters and numbers.',
  'settings.password.validation.confirm': 'Password confirmation is required.',
  'settings.password.validation.match': 'Passwords do not match.',
  'settings.password.note.title': 'Security behavior',
  'settings.password.note.text':
    'After a successful password change, TransitOps closes the current session and asks you to sign in again.',
  'settings.password.updating': 'Updating...',
  'settings.password.change': 'Change password',
  'settings.password.success': 'Password updated successfully. Please sign in again.',
  'settings.password.error.update': 'Password could not be updated.',

  'settings.language.kicker': 'Localization',
  'settings.language.note.title': 'UI preference',
  'settings.language.note.text':
    'This setting changes the main interface text between English and Spanish without affecting data, roles or permissions.',

  'navbar.openSidebar': 'Open sidebar',
  'navbar.title': 'TransitOps Control Panel',
  'navbar.subtitle': 'Administrative transportation operations dashboard',
  'navbar.logout': 'Logout',
  'navbar.profile': 'Profile',
  'navbar.profile.description': 'Manage your personal information',
  'navbar.settings': 'Settings',
  'navbar.settings.description': 'Language and account preferences',
  'navbar.logout.description': 'Close this session',
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Operational summary for TransitOps Platform.',
  'dashboard.loading': 'Loading dashboard data...',
  'dashboard.error.load': 'Unable to load dashboard data.',
  'dashboard.metric.totalVehicles': 'Total Vehicles',
  'dashboard.metric.availableVehicles': 'Available Vehicles',
  'dashboard.metric.activeDrivers': 'Active Drivers',
  'dashboard.metric.activeRoutes': 'Active Routes',
  'dashboard.metric.ready': 'Ready',
  'dashboard.fleetStatus': 'Fleet status',
  'dashboard.driverStatus': 'Driver status',
  'dashboard.tripStatus': 'Trip status',
  'dashboard.latestTrips.title': 'Latest trips',
  'dashboard.latestTrips.subtitle': 'Most recent scheduled transportation operations.',
  'dashboard.emptyTrips.title': 'No trips yet',
  'dashboard.emptyTrips.message': 'There are no trips scheduled at this moment.',
  'dashboard.quickActions': 'Quick actions',
  'dashboard.operationalRule.label': 'Operational rule:',
  'dashboard.operationalRule.text':
    'Trips can only be scheduled with available vehicles, active drivers and active routes.',
  'vehicles.title': 'Vehicles',
  'vehicles.subtitle': 'Manage fleet availability and operational status.',
  'vehicles.create': 'Create vehicle',
  'vehicles.search.label': 'Search vehicles',
  'vehicles.search.placeholder': 'Search by unit number, brand or model',
  'vehicles.summary.label': 'vehicles',
  'vehicles.loading': 'Loading vehicles...',
  'vehicles.empty.title': 'No vehicles found',
  'vehicles.empty.message': 'There are no vehicles registered yet.',
  'vehicles.error.load': 'Unable to load vehicles.',
  'vehicles.error.update': 'Unable to update vehicle status.',
  'vehicles.success.update': 'Vehicle status updated successfully.',
  'vehicles.form.title': 'New Vehicle',
  'vehicles.form.subtitle': 'Register a new vehicle for TransitOps Platform.',
  'vehicles.form.unitNumber': 'Unit Number',
  'vehicles.form.brand': 'Brand',
  'vehicles.form.model': 'Model',
  'vehicles.form.year': 'Year',
  'vehicles.form.capacity': 'Capacity',
  'vehicles.form.lastMaintenanceDate': 'Last maintenance date',
  'vehicles.form.save': 'Save Vehicle',
  'vehicles.error.create': 'Unable to create vehicle.',
  'vehicles.validation.unitNumberRequired': 'Unit number is required.',
  'vehicles.validation.unitNumberMin': 'Unit number must have at least 3 characters.',
  'vehicles.validation.unitNumberMax': 'Unit number cannot exceed 20 characters.',
  'vehicles.validation.brandRequired': 'Brand is required.',
  'vehicles.validation.brandMax': 'Brand cannot exceed 60 characters.',
  'vehicles.validation.modelRequired': 'Model is required.',
  'vehicles.validation.modelMax': 'Model cannot exceed 60 characters.',
  'vehicles.validation.yearRequired': 'Year is required.',
  'vehicles.validation.yearValid': 'Enter a valid vehicle year.',
  'vehicles.validation.capacityRequired': 'Capacity is required.',
  'vehicles.validation.capacityRange': 'Capacity must be between 1 and 120.',
  'vehicles.validation.statusRequired': 'Status is required.',
  'drivers.title': 'Drivers',
  'drivers.subtitle': 'Manage drivers, licenses and operational status.',
  'drivers.create': 'New Driver',
  'drivers.search.label': 'Search drivers',
  'drivers.search.placeholder': 'Search by name, license, email or phone',
  'drivers.summary.label': 'drivers',
  'drivers.loading': 'Loading drivers...',
  'drivers.empty.title': 'No drivers found',
  'drivers.empty.message': 'There are no drivers registered yet.',
  'drivers.error.load': 'Unable to load drivers.',
  'drivers.error.update': 'Unable to update driver status.',
  'drivers.success.update': 'Driver status updated successfully.',
  'drivers.action.suspend': 'Suspend',
  'drivers.form.title': 'New Driver',
  'drivers.form.subtitle': 'Register a new driver and define operational status.',
  'drivers.form.firstName': 'First name',
  'drivers.form.lastName': 'Last name',
  'drivers.form.licenseNumber': 'License number',
  'drivers.form.save': 'Save Driver',
  'drivers.error.create': 'Unable to create driver.',
  'drivers.validation.firstNameRequired': 'First name is required.',
  'drivers.validation.firstNameMin': 'First name must have at least 2 characters.',
  'drivers.validation.firstNameMax': 'First name cannot exceed 60 characters.',
  'drivers.validation.lastNameRequired': 'Last name is required.',
  'drivers.validation.lastNameMin': 'Last name must have at least 2 characters.',
  'drivers.validation.lastNameMax': 'Last name cannot exceed 60 characters.',
  'drivers.validation.licenseRequired': 'License number is required.',
  'drivers.validation.licenseMin': 'License number must have at least 4 characters.',
  'drivers.validation.licenseMax': 'License number cannot exceed 30 characters.',
  'drivers.validation.phoneRequired': 'Phone is required.',
  'drivers.validation.phoneValid': 'Enter a valid phone number.',
  'drivers.validation.emailRequired': 'Email is required.',
  'drivers.validation.emailValid': 'Enter a valid email address.',
  'drivers.validation.emailMax': 'Email cannot exceed 100 characters.',
  'drivers.validation.statusRequired': 'Status is required.',
  'routes.title': 'Routes',
  'routes.subtitle': 'Manage available operational routes.',
  'routes.create': 'New Route',
  'routes.search.label': 'Search routes',
  'routes.search.placeholder': 'Search by name, origin or destination',
  'routes.filter.statusTitle': 'Status filter',
  'routes.summary.label': 'routes',
  'routes.loading': 'Loading routes...',
  'routes.empty.title': 'No routes found',
  'routes.empty.message': 'There are no routes registered yet.',
  'routes.error.load': 'Unable to load routes.',
  'routes.error.update': 'Unable to update route status.',
  'routes.success.update': 'Route status updated successfully.',
  'routes.action.activate': 'Activate',
  'routes.action.deactivate': 'Deactivate',
  'routes.form.title': 'New Route',
  'routes.form.subtitle': 'Create an operational route available for trip scheduling.',
  'routes.form.name': 'Route name',
  'routes.form.origin': 'Origin',
  'routes.form.destination': 'Destination',
  'routes.form.distanceKm': 'Distance Km',
  'routes.form.estimatedDurationMinutes': 'Estimated duration minutes',
  'routes.form.save': 'Save Route',
  'routes.error.create': 'Unable to create route.',
  'routes.validation.nameRequired': 'Route name is required.',
  'routes.validation.nameMin': 'Route name must have at least 3 characters.',
  'routes.validation.nameMax': 'Route name cannot exceed 80 characters.',
  'routes.validation.statusRequired': 'Status is required.',
  'routes.validation.originRequired': 'Origin is required.',
  'routes.validation.originMin': 'Origin must have at least 3 characters.',
  'routes.validation.originMax': 'Origin cannot exceed 100 characters.',
  'routes.validation.destinationRequired': 'Destination is required.',
  'routes.validation.destinationMin': 'Destination must have at least 3 characters.',
  'routes.validation.destinationMax': 'Destination cannot exceed 100 characters.',
  'routes.validation.distanceRequired': 'Distance is required.',
  'routes.validation.distanceRange': 'Distance must be between 1 and 5000 km.',
  'routes.validation.durationRequired': 'Estimated duration is required.',
  'routes.validation.durationRange': 'Duration must be between 1 and 1440 minutes.',
  'trips.title': 'Trips',
  'trips.subtitle': 'Schedule, monitor and update transportation trips.',
  'trips.create': 'New Trip',
  'trips.search.label': 'Search trips',
  'trips.search.placeholder': 'Search by vehicle, driver, route or notes',
  'trips.summary.label': 'trips',
  'trips.loading': 'Loading trips...',
  'trips.empty.title': 'No trips found',
  'trips.empty.message': 'There are no trips scheduled yet.',
  'trips.error.load': 'Unable to load trips.',
  'trips.error.update': 'Unable to update trip status.',
  'trips.success.update': 'Trip status updated successfully.',
  'trips.table.scheduledDeparture': 'Scheduled Departure',
  'trips.action.start': 'Start',
  'trips.action.complete': 'Complete',
  'trips.action.cancel': 'Cancel',
  'trips.form.title': 'New Trip',
  'trips.form.subtitle':
    'Schedule a new trip using an available vehicle, active driver and active route.',
  'trips.form.loadingResources': 'Loading available resources...',
  'trips.form.notEnough.title': 'Not enough available resources',
  'trips.form.notEnough.message':
    'You need at least one available vehicle, one active driver and one active route to schedule a trip.',
  'trips.form.availableVehicles': 'Available vehicles',
  'trips.form.activeDrivers': 'Active drivers',
  'trips.form.activeRoutes': 'Active routes',
  'trips.form.selectVehicle': 'Select vehicle',
  'trips.form.selectDriver': 'Select driver',
  'trips.form.selectRoute': 'Select route',
  'trips.form.scheduledDeparture': 'Scheduled departure',
  'trips.form.notesPlaceholder': 'Optional trip notes...',
  'trips.form.businessRules.title': 'Business rules applied',
  'trips.form.businessRules.vehicle': 'Only available vehicles can be selected.',
  'trips.form.businessRules.driver': 'Only active drivers can be selected.',
  'trips.form.businessRules.route': 'Only active routes can be selected.',
  'trips.form.businessRules.backend':
    'The Back-End validates the final operation before creating the trip.',
  'trips.form.scheduling': 'Scheduling...',
  'trips.form.schedule': 'Schedule Trip',
  'trips.error.loadForm': 'Unable to load trip form data.',
  'trips.error.create': 'Unable to create trip.',
  'trips.validation.vehicleRequired': 'Vehicle is required.',
  'trips.validation.driverRequired': 'Driver is required.',
  'trips.validation.routeRequired': 'Route is required.',
  'trips.validation.departureRequired': 'Scheduled departure is required.',
  'admin.title': 'Admin',
  'admin.subtitle': 'Administrative tools and platform configuration.',
  'admin.panel.title': 'Admin panel',
  'admin.panel.description':
    'This section centralizes operational administration. More modules can be added here as the platform evolves.',
  'role.admin': 'Admin',
  'role.operator': 'Operator',
  'role.supervisor': 'Supervisor',
  'role.viewer': 'Viewer',
  'users.title': 'Users',
  'users.subtitle': 'Review registration requests and manage account access.',
  'users.summary.title': 'Users summary',
  'users.summary.total': 'Total users',
  'users.summary.active': 'Active users',
  'users.summary.pending': 'Pending approval',
  'users.summary.restricted': 'Rejected/Suspended',
  'users.summary.label': 'users',
  'users.search.label': 'Search users',
  'users.search.placeholder': 'Search by name, email or phone',
  'users.filters.role': 'Role',
  'users.filters.allRoles': 'All roles',
  'users.loading': 'Loading users...',
  'users.empty.title': 'No users found',
  'users.empty.message': 'No users match the current filters.',
  'users.table.currentRole': 'Current role',
  'users.table.requestedRole': 'Requested role',
  'users.table.createdAt': 'Created',
  'users.table.noPhone': 'No phone',
  'users.table.noDate': 'No date',
  'users.table.notRequested': 'Not requested',
  'users.actions.approve': 'Approve',
  'users.actions.reject': 'Reject',
  'users.actions.suspend': 'Suspend',
  'users.actions.reactivate': 'Reactivate',
  'users.actions.deactivate': 'Deactivate',
  'users.confirm.reject': 'Reject this pending user?',
  'users.confirm.suspend': 'Suspend this active user?',
  'users.confirm.reactivate': 'Reactivate this user?',
  'users.confirm.deactivate': 'Deactivate this user?',
  'users.success.approve': 'User approved successfully.',
  'users.success.reject': 'User rejected successfully.',
  'users.success.status': 'User status updated successfully.',
  'users.error.load': 'Unable to load users.',
  'users.error.update': 'Unable to update user.',
  'auth.login.welcome': 'Welcome back',
  'auth.login.subtitle': 'Sign in to TransitOps Control Panel.',
  'auth.login.email': 'Email',
  'auth.login.password': 'Password',
  'auth.login.signingIn': 'Signing in...',
  'auth.login.signIn': 'Sign in',
  'auth.login.demoUsers': 'Demo users',
  'auth.login.error': 'Unable to sign in. Please try again.',
  'auth.login.noAccount': 'Do not have an account?',
  'auth.login.createAccount': 'Create account',
  'auth.register.title': 'Create your account',
  'auth.register.subtitle': 'Request access to TransitOps Control Panel.',
  'auth.register.personalInfo': 'Personal information',
  'auth.register.accountAccess': 'Account access',
  'auth.register.verification': 'Verification',
  'auth.register.requestedRole': 'Requested role',
  'auth.register.firstName': 'First name',
  'auth.register.lastName': 'Last name',
  'auth.register.phone': 'Phone',
  'auth.register.confirmPassword': 'Confirm password',
  'auth.register.emailCode': 'Email code',
  'auth.register.phoneCode': 'Phone code',
  'auth.register.sendEmailCode': 'Send email code',
  'auth.register.sendingEmailCode': 'Sending email code...',
  'auth.register.sendPhoneCode': 'Send phone code',
  'auth.register.sendingPhoneCode': 'Sending phone code...',
  'auth.register.mockCodesNote': 'Development mock codes only: email 123456 and phone 654321.',
  'auth.register.roleLabel': 'Select the access level to request',
  'auth.register.roleViewer': 'Viewer',
  'auth.register.roleOperator': 'Operator',
  'auth.register.roleSupervisor': 'Supervisor',
  'auth.register.registerAccount': 'Register account',
  'auth.register.registering': 'Registering account...',
  'auth.register.haveAccount': 'Already have an account?',
  'auth.register.signIn': 'Sign in',
  'auth.register.successTitle': 'Registration successful',
  'auth.register.successMessage':
    'Your account was created with the requested role. You can now return to login.',
  'auth.register.successActiveMessage': 'Your viewer account is active. You can now sign in.',
  'auth.register.successPendingMessage':
    'Your account was created and is pending administrator approval before sign-in.',
  'auth.register.goToLogin': 'Go to login',
  'auth.register.emailCodeSent': 'Email code sent. Use mock code 123456.',
  'auth.register.phoneCodeSent': 'Phone code sent. Use mock code 654321.',
  'auth.register.emailCodeError': 'Unable to send email code. Please try again.',
  'auth.register.phoneCodeError': 'Unable to send phone code. Please try again.',
  'auth.register.error': 'Unable to register account. Please try again.',
  'auth.validation.emailRequired': 'Email is required.',
  'auth.validation.emailValid': 'Enter a valid email address.',
  'auth.validation.passwordRequired': 'Password is required.',
  'auth.validation.firstNameRequired': 'First name is required.',
  'auth.validation.lastNameRequired': 'Last name is required.',
  'auth.validation.phoneRequired': 'Phone is required.',
  'auth.validation.phoneValid': 'Enter a valid phone number.',
  'auth.validation.emailCodeRequired': 'Email code is required.',
  'auth.validation.phoneCodeRequired': 'Phone code is required.',
  'auth.validation.passwordMinLength': 'Password must have at least 8 characters.',
  'auth.validation.confirmPasswordRequired': 'Confirm password is required.',
  'auth.validation.passwordMatch': 'Passwords must match.',
  'auth.validation.requestedRoleRequired': 'Requested role is required.',
  'auth.accessDenied.title': 'Access denied',
  'auth.accessDenied.message': 'You do not have permission to access this resource.',
  'status.available': 'Available',
  'status.maintenance': 'Maintenance',
  'status.inactive': 'Inactive',
  'status.active': 'Active',
  'status.pendingApproval': 'Pending approval',
  'status.rejected': 'Rejected',
  'status.suspended': 'Suspended',
  'status.scheduled': 'Scheduled',
  'status.inProgress': 'In progress',
  'status.completed': 'Completed',
  'status.cancelled': 'Cancelled',
} as const;

export type TranslationKey = keyof typeof enTranslations;

const esTranslations: Record<TranslationKey, string> = {
  'common.actions': 'Acciones',
  'common.allStatuses': 'Todos los estados',
  'common.backToDashboard': 'Volver al panel',
  'common.cancel': 'Cancelar',
  'common.clear': 'Limpiar',
  'common.destination': 'Destino',
  'common.distance': 'Distancia',
  'common.driver': 'Conductor',
  'common.email': 'Correo',
  'common.estimatedDuration': 'Duración estimada',
  'common.loading': 'Cargando...',
  'common.loadingData': 'Cargando datos...',
  'common.name': 'Nombre',
  'common.noActions': 'Sin acciones',
  'common.notes': 'Notas',
  'common.of': 'de',
  'common.origin': 'Origen',
  'common.phone': 'Teléfono',
  'common.route': 'Ruta',
  'common.saving': 'Guardando...',
  'common.search': 'Buscar',
  'common.showing': 'Mostrando',
  'common.status': 'Estado',
  'common.vehicle': 'Vehículo',
  'common.view': 'Ver',
  'common.viewAll': 'Ver todo',
  'common.viewOnly': 'Solo lectura',
  'empty.defaultMessage': 'Todavía no hay información para mostrar.',
  'empty.defaultTitle': 'No se encontraron registros',
  'sidebar.brand.subtitle': 'Panel de control',
  'sidebar.close': 'Cerrar menú lateral',
  'sidebar.dashboard': 'Panel',
  'sidebar.vehicles': 'Vehículos',
  'sidebar.drivers': 'Conductores',
  'sidebar.routes': 'Rutas',
  'sidebar.trips': 'Viajes',
  'sidebar.admin': 'Administración',
  'sidebar.users': 'Usuarios',
  'sidebar.settings': 'Configuración',
  'sidebar.theme.light': 'Modo claro',
  'sidebar.theme.dark': 'Modo oscuro',
  'sidebar.theme.switchToLight': 'Cambiar a tema claro',
  'sidebar.theme.switchToDark': 'Cambiar a tema oscuro',
  'sidebar.meta.project': 'Plataforma TransitOps',
  'sidebar.meta.description': 'Sistema administrativo Angular',
  'settings.title': 'Configuración',
  'settings.subtitle': 'Administra tus preferencias personales de TransitOps.',
    'settings.home.kicker': 'Preferencias del espacio de trabajo',
  'settings.home.title': 'Elige qué quieres configurar',
  'settings.home.description':
    'Administra tu perfil de cuenta y el idioma de la interfaz desde secciones enfocadas para mantener TransitOps simple y predecible.',
  'settings.home.profile.title': 'Perfil',
  'settings.home.profile.description':
    'Actualiza tu información personal, avatar, correo, teléfono y configuración de seguridad de contraseña.',
  'settings.home.language.title': 'Idioma',
  'settings.home.language.description':
    'Elige el idioma de la interfaz usado en navegación, configuración y pantallas operativas.',
  'settings.home.openSection': 'Abrir sección',
  'settings.language.title': 'Idioma',
  'settings.language.description': 'Elige el idioma de navegación y configuración.',
  'settings.language.english': 'Inglés',
  'settings.language.spanish': 'Español',
  'settings.language.current': 'Idioma actual',

  'settings.account.kicker': 'Centro de cuenta',
  'settings.account.profileFallbackTitle': 'Perfil',
  'settings.account.fallbackDescription':
    'Administra tu información personal y configuración de seguridad.',
  'settings.account.role': 'Rol',
  'settings.account.status': 'Estado',

  'settings.avatar.kicker': 'Avatar',
  'settings.avatar.title': 'Foto de perfil',
  'settings.avatar.description': 'Sube una imagen JPEG, PNG o WebP para personalizar tu cuenta.',
  'settings.avatar.recommended':
    'Recomendado: imagen cuadrada, máximo 2 MB. Formatos permitidos: JPEG, PNG y WebP.',
  'settings.avatar.upload': 'Subir foto',
  'settings.avatar.uploading': 'Subiendo...',
  'settings.avatar.remove': 'Eliminar foto',
  'settings.avatar.removing': 'Eliminando...',
  'settings.avatar.success.update': 'Avatar actualizado correctamente.',
  'settings.avatar.success.delete': 'Avatar eliminado correctamente.',
  'settings.avatar.error.invalidType': 'El avatar debe ser una imagen JPEG, PNG o WebP.',
  'settings.avatar.error.tooLarge': 'El archivo de avatar no debe superar 2 MB.',
  'settings.avatar.error.none': 'No hay avatar para eliminar.',
  'settings.avatar.error.update': 'No se pudo actualizar el avatar.',
  'settings.avatar.error.delete': 'No se pudo eliminar el avatar.',

  'settings.profile.kicker': 'Perfil',
  'settings.profile.title': 'Información personal',
  'settings.profile.description': 'Actualiza tu nombre, correo y teléfono usados en TransitOps.',
  'settings.profile.firstName': 'Nombre',
  'settings.profile.lastName': 'Apellido',
  'settings.profile.email': 'Correo',
  'settings.profile.phone': 'Teléfono',
  'settings.profile.currentPassword': 'Contraseña actual',
  'settings.profile.currentPasswordPlaceholder': 'Requerida solo al cambiar el correo',
  'settings.profile.currentPasswordHint':
    'Por seguridad, los cambios de correo requieren tu contraseña actual.',
  'settings.profile.validation.name': 'El nombre debe contener entre 2 y 60 caracteres.',
  'settings.profile.validation.email': 'Ingresa un correo válido.',
  'settings.profile.validation.phone': 'El teléfono debe contener entre 8 y 25 caracteres.',
  'settings.profile.saving': 'Guardando...',
  'settings.profile.save': 'Guardar perfil',
  'settings.profile.success': 'Perfil actualizado correctamente.',
  'settings.profile.error.noUser': 'No hay un usuario autenticado cargado.',
  'settings.profile.error.emailPasswordRequired':
    'La contraseña actual es requerida al cambiar tu correo.',
  'settings.profile.error.update': 'No se pudo actualizar el perfil.',

  'settings.password.kicker': 'Seguridad',
  'settings.password.title': 'Contraseña',
  'settings.password.description': 'Cambia tu contraseña usando tus credenciales actuales.',
  'settings.password.current': 'Contraseña actual',
  'settings.password.new': 'Nueva contraseña',
  'settings.password.confirm': 'Confirmar contraseña',
  'settings.password.validation.current': 'La contraseña actual es obligatoria.',
  'settings.password.validation.new': 'Usa al menos 8 caracteres, incluyendo letras y números.',
  'settings.password.validation.confirm': 'La confirmación de contraseña es obligatoria.',
  'settings.password.validation.match': 'Las contraseñas no coinciden.',
  'settings.password.note.title': 'Comportamiento de seguridad',
  'settings.password.note.text':
    'Después de cambiar la contraseña correctamente, TransitOps cierra la sesión actual y te pide iniciar sesión nuevamente.',
  'settings.password.updating': 'Actualizando...',
  'settings.password.change': 'Cambiar contraseña',
  'settings.password.success': 'Contraseña actualizada correctamente. Inicia sesión nuevamente.',
  'settings.password.error.update': 'No se pudo actualizar la contraseña.',

  'settings.language.kicker': 'Localización',
  'settings.language.note.title': 'Preferencia de interfaz',
  'settings.language.note.text':
    'Este ajuste cambia los textos principales de la interfaz entre inglés y español sin afectar datos, roles ni permisos.',

  'navbar.openSidebar': 'Abrir menú lateral',
  'navbar.title': 'Panel de control TransitOps',
  'navbar.subtitle': 'Panel administrativo para operaciones de transporte',
  'navbar.logout': 'Cerrar sesión',
  'navbar.profile': 'Perfil',
  'navbar.profile.description': 'Administra tu información personal',
  'navbar.settings': 'Configuración',
  'navbar.settings.description': 'Idioma y preferencias de cuenta',
  'navbar.logout.description': 'Cerrar esta sesión',
  'dashboard.title': 'Panel',
  'dashboard.subtitle': 'Resumen operativo de TransitOps Platform.',
  'dashboard.loading': 'Cargando datos del panel...',
  'dashboard.error.load': 'No se pudieron cargar los datos del panel.',
  'dashboard.metric.totalVehicles': 'Total de vehículos',
  'dashboard.metric.availableVehicles': 'Vehículos disponibles',
  'dashboard.metric.activeDrivers': 'Conductores activos',
  'dashboard.metric.activeRoutes': 'Rutas activas',
  'dashboard.metric.ready': 'Listos',
  'dashboard.fleetStatus': 'Estado de la flota',
  'dashboard.driverStatus': 'Estado de conductores',
  'dashboard.tripStatus': 'Estado de viajes',
  'dashboard.latestTrips.title': 'Últimos viajes',
  'dashboard.latestTrips.subtitle': 'Operaciones de transporte programadas más recientes.',
  'dashboard.emptyTrips.title': 'Aún no hay viajes',
  'dashboard.emptyTrips.message': 'No hay viajes programados en este momento.',
  'dashboard.quickActions': 'Acciones rápidas',
  'dashboard.operationalRule.label': 'Regla operativa:',
  'dashboard.operationalRule.text':
    'Los viajes solo pueden programarse con vehículos disponibles, conductores activos y rutas activas.',
  'vehicles.title': 'Vehículos',
  'vehicles.subtitle': 'Gestiona la disponibilidad y el estado operativo de la flota.',
  'vehicles.create': 'Crear vehículo',
  'vehicles.search.label': 'Buscar vehículos',
  'vehicles.search.placeholder': 'Buscar por número de unidad, marca o modelo',
  'vehicles.summary.label': 'vehículos',
  'vehicles.loading': 'Cargando vehículos...',
  'vehicles.empty.title': 'No se encontraron vehículos',
  'vehicles.empty.message': 'Todavía no hay vehículos registrados.',
  'vehicles.error.load': 'No se pudieron cargar los vehículos.',
  'vehicles.error.update': 'No se pudo actualizar el estado del vehículo.',
  'vehicles.success.update': 'Estado del vehículo actualizado correctamente.',
  'vehicles.form.title': 'Nuevo vehículo',
  'vehicles.form.subtitle': 'Registra un nuevo vehículo para TransitOps Platform.',
  'vehicles.form.unitNumber': 'Número de unidad',
  'vehicles.form.brand': 'Marca',
  'vehicles.form.model': 'Modelo',
  'vehicles.form.year': 'Año',
  'vehicles.form.capacity': 'Capacidad',
  'vehicles.form.lastMaintenanceDate': 'Fecha de último mantenimiento',
  'vehicles.form.save': 'Guardar vehículo',
  'vehicles.error.create': 'No se pudo crear el vehículo.',
  'vehicles.validation.unitNumberRequired': 'El número de unidad es obligatorio.',
  'vehicles.validation.unitNumberMin': 'El número de unidad debe tener al menos 3 caracteres.',
  'vehicles.validation.unitNumberMax': 'El número de unidad no puede exceder 20 caracteres.',
  'vehicles.validation.brandRequired': 'La marca es obligatoria.',
  'vehicles.validation.brandMax': 'La marca no puede exceder 60 caracteres.',
  'vehicles.validation.modelRequired': 'El modelo es obligatorio.',
  'vehicles.validation.modelMax': 'El modelo no puede exceder 60 caracteres.',
  'vehicles.validation.yearRequired': 'El año es obligatorio.',
  'vehicles.validation.yearValid': 'Ingresa un año válido para el vehículo.',
  'vehicles.validation.capacityRequired': 'La capacidad es obligatoria.',
  'vehicles.validation.capacityRange': 'La capacidad debe estar entre 1 y 120.',
  'vehicles.validation.statusRequired': 'El estado es obligatorio.',
  'drivers.title': 'Conductores',
  'drivers.subtitle': 'Gestiona conductores, licencias y estado operativo.',
  'drivers.create': 'Nuevo conductor',
  'drivers.search.label': 'Buscar conductores',
  'drivers.search.placeholder': 'Buscar por nombre, licencia, correo o teléfono',
  'drivers.summary.label': 'conductores',
  'drivers.loading': 'Cargando conductores...',
  'drivers.empty.title': 'No se encontraron conductores',
  'drivers.empty.message': 'Todavía no hay conductores registrados.',
  'drivers.error.load': 'No se pudieron cargar los conductores.',
  'drivers.error.update': 'No se pudo actualizar el estado del conductor.',
  'drivers.success.update': 'Estado del conductor actualizado correctamente.',
  'drivers.action.suspend': 'Suspender',
  'drivers.form.title': 'Nuevo conductor',
  'drivers.form.subtitle': 'Registra un nuevo conductor y define su estado operativo.',
  'drivers.form.firstName': 'Nombre',
  'drivers.form.lastName': 'Apellido',
  'drivers.form.licenseNumber': 'Número de licencia',
  'drivers.form.save': 'Guardar conductor',
  'drivers.error.create': 'No se pudo crear el conductor.',
  'drivers.validation.firstNameRequired': 'El nombre es obligatorio.',
  'drivers.validation.firstNameMin': 'El nombre debe tener al menos 2 caracteres.',
  'drivers.validation.firstNameMax': 'El nombre no puede exceder 60 caracteres.',
  'drivers.validation.lastNameRequired': 'El apellido es obligatorio.',
  'drivers.validation.lastNameMin': 'El apellido debe tener al menos 2 caracteres.',
  'drivers.validation.lastNameMax': 'El apellido no puede exceder 60 caracteres.',
  'drivers.validation.licenseRequired': 'El número de licencia es obligatorio.',
  'drivers.validation.licenseMin': 'El número de licencia debe tener al menos 4 caracteres.',
  'drivers.validation.licenseMax': 'El número de licencia no puede exceder 30 caracteres.',
  'drivers.validation.phoneRequired': 'El teléfono es obligatorio.',
  'drivers.validation.phoneValid': 'Ingresa un número de teléfono válido.',
  'drivers.validation.emailRequired': 'El correo es obligatorio.',
  'drivers.validation.emailValid': 'Ingresa un correo válido.',
  'drivers.validation.emailMax': 'El correo no puede exceder 100 caracteres.',
  'drivers.validation.statusRequired': 'El estado es obligatorio.',
  'routes.title': 'Rutas',
  'routes.subtitle': 'Gestiona las rutas operativas disponibles.',
  'routes.create': 'Nueva ruta',
  'routes.search.label': 'Buscar rutas',
  'routes.search.placeholder': 'Buscar por nombre, origen o destino',
  'routes.filter.statusTitle': 'Filtro de estado',
  'routes.summary.label': 'rutas',
  'routes.loading': 'Cargando rutas...',
  'routes.empty.title': 'No se encontraron rutas',
  'routes.empty.message': 'Todavía no hay rutas registradas.',
  'routes.error.load': 'No se pudieron cargar las rutas.',
  'routes.error.update': 'No se pudo actualizar el estado de la ruta.',
  'routes.success.update': 'Estado de la ruta actualizado correctamente.',
  'routes.action.activate': 'Activar',
  'routes.action.deactivate': 'Desactivar',
  'routes.form.title': 'Nueva ruta',
  'routes.form.subtitle': 'Crea una ruta operativa disponible para programar viajes.',
  'routes.form.name': 'Nombre de la ruta',
  'routes.form.origin': 'Origen',
  'routes.form.destination': 'Destino',
  'routes.form.distanceKm': 'Distancia Km',
  'routes.form.estimatedDurationMinutes': 'Duración estimada en minutos',
  'routes.form.save': 'Guardar ruta',
  'routes.error.create': 'No se pudo crear la ruta.',
  'routes.validation.nameRequired': 'El nombre de la ruta es obligatorio.',
  'routes.validation.nameMin': 'El nombre de la ruta debe tener al menos 3 caracteres.',
  'routes.validation.nameMax': 'El nombre de la ruta no puede exceder 80 caracteres.',
  'routes.validation.statusRequired': 'El estado es obligatorio.',
  'routes.validation.originRequired': 'El origen es obligatorio.',
  'routes.validation.originMin': 'El origen debe tener al menos 3 caracteres.',
  'routes.validation.originMax': 'El origen no puede exceder 100 caracteres.',
  'routes.validation.destinationRequired': 'El destino es obligatorio.',
  'routes.validation.destinationMin': 'El destino debe tener al menos 3 caracteres.',
  'routes.validation.destinationMax': 'El destino no puede exceder 100 caracteres.',
  'routes.validation.distanceRequired': 'La distancia es obligatoria.',
  'routes.validation.distanceRange': 'La distancia debe estar entre 1 y 5000 km.',
  'routes.validation.durationRequired': 'La duración estimada es obligatoria.',
  'routes.validation.durationRange': 'La duración debe estar entre 1 y 1440 minutos.',
  'trips.title': 'Viajes',
  'trips.subtitle': 'Programa, monitorea y actualiza viajes de transporte.',
  'trips.create': 'Nuevo viaje',
  'trips.search.label': 'Buscar viajes',
  'trips.search.placeholder': 'Buscar por vehículo, conductor, ruta o notas',
  'trips.summary.label': 'viajes',
  'trips.loading': 'Cargando viajes...',
  'trips.empty.title': 'No se encontraron viajes',
  'trips.empty.message': 'Todavía no hay viajes programados.',
  'trips.error.load': 'No se pudieron cargar los viajes.',
  'trips.error.update': 'No se pudo actualizar el estado del viaje.',
  'trips.success.update': 'Estado del viaje actualizado correctamente.',
  'trips.table.scheduledDeparture': 'Salida programada',
  'trips.action.start': 'Iniciar',
  'trips.action.complete': 'Completar',
  'trips.action.cancel': 'Cancelar',
  'trips.form.title': 'Nuevo viaje',
  'trips.form.subtitle':
    'Programa un nuevo viaje con un vehículo disponible, un conductor activo y una ruta activa.',
  'trips.form.loadingResources': 'Cargando recursos disponibles...',
  'trips.form.notEnough.title': 'No hay suficientes recursos disponibles',
  'trips.form.notEnough.message':
    'Necesitas al menos un vehículo disponible, un conductor activo y una ruta activa para programar un viaje.',
  'trips.form.availableVehicles': 'Vehículos disponibles',
  'trips.form.activeDrivers': 'Conductores activos',
  'trips.form.activeRoutes': 'Rutas activas',
  'trips.form.selectVehicle': 'Selecciona un vehículo',
  'trips.form.selectDriver': 'Selecciona un conductor',
  'trips.form.selectRoute': 'Selecciona una ruta',
  'trips.form.scheduledDeparture': 'Salida programada',
  'trips.form.notesPlaceholder': 'Notas opcionales del viaje...',
  'trips.form.businessRules.title': 'Reglas de negocio aplicadas',
  'trips.form.businessRules.vehicle': 'Solo se pueden seleccionar vehículos disponibles.',
  'trips.form.businessRules.driver': 'Solo se pueden seleccionar conductores activos.',
  'trips.form.businessRules.route': 'Solo se pueden seleccionar rutas activas.',
  'trips.form.businessRules.backend':
    'El Back-End valida la operación final antes de crear el viaje.',
  'trips.form.scheduling': 'Programando...',
  'trips.form.schedule': 'Programar viaje',
  'trips.error.loadForm': 'No se pudieron cargar los datos del formulario de viaje.',
  'trips.error.create': 'No se pudo crear el viaje.',
  'trips.validation.vehicleRequired': 'El vehículo es obligatorio.',
  'trips.validation.driverRequired': 'El conductor es obligatorio.',
  'trips.validation.routeRequired': 'La ruta es obligatoria.',
  'trips.validation.departureRequired': 'La salida programada es obligatoria.',
  'admin.title': 'Administración',
  'admin.subtitle': 'Herramientas administrativas y configuración de la plataforma.',
  'admin.panel.title': 'Panel administrativo',
  'admin.panel.description':
    'Esta sección centraliza la administración operativa. Se pueden agregar más módulos conforme la plataforma evolucione.',
  'role.admin': 'Administrador',
  'role.operator': 'Operador',
  'role.supervisor': 'Supervisor',
  'role.viewer': 'Consulta',
  'users.title': 'Usuarios',
  'users.subtitle': 'Revisa solicitudes de registro y administra el acceso de cuentas.',
  'users.summary.title': 'Resumen de usuarios',
  'users.summary.total': 'Total de usuarios',
  'users.summary.active': 'Usuarios activos',
  'users.summary.pending': 'Pendientes de aprobación',
  'users.summary.restricted': 'Rechazados/Suspendidos',
  'users.summary.label': 'usuarios',
  'users.search.label': 'Buscar usuarios',
  'users.search.placeholder': 'Buscar por nombre, correo o teléfono',
  'users.filters.role': 'Rol',
  'users.filters.allRoles': 'Todos los roles',
  'users.loading': 'Cargando usuarios...',
  'users.empty.title': 'No se encontraron usuarios',
  'users.empty.message': 'Ningún usuario coincide con los filtros actuales.',
  'users.table.currentRole': 'Rol actual',
  'users.table.requestedRole': 'Rol solicitado',
  'users.table.createdAt': 'Creado',
  'users.table.noPhone': 'Sin teléfono',
  'users.table.noDate': 'Sin fecha',
  'users.table.notRequested': 'No solicitado',
  'users.actions.approve': 'Aprobar',
  'users.actions.reject': 'Rechazar',
  'users.actions.suspend': 'Suspender',
  'users.actions.reactivate': 'Reactivar',
  'users.actions.deactivate': 'Desactivar',
  'users.confirm.reject': '¿Rechazar este usuario pendiente?',
  'users.confirm.suspend': '¿Suspender este usuario activo?',
  'users.confirm.reactivate': '¿Reactivar este usuario?',
  'users.confirm.deactivate': '¿Desactivar este usuario?',
  'users.success.approve': 'Usuario aprobado correctamente.',
  'users.success.reject': 'Usuario rechazado correctamente.',
  'users.success.status': 'Estado del usuario actualizado correctamente.',
  'users.error.load': 'No se pudieron cargar los usuarios.',
  'users.error.update': 'No se pudo actualizar el usuario.',
  'auth.login.welcome': 'Bienvenido de nuevo',
  'auth.login.subtitle': 'Inicia sesión en TransitOps Control Panel.',
  'auth.login.email': 'Correo',
  'auth.login.password': 'Contraseña',
  'auth.login.signingIn': 'Iniciando sesión...',
  'auth.login.signIn': 'Iniciar sesión',
  'auth.login.demoUsers': 'Usuarios demo',
  'auth.login.error': 'No se pudo iniciar sesión. Inténtalo de nuevo.',
  'auth.login.noAccount': '¿No tienes cuenta?',
  'auth.login.createAccount': 'Crear cuenta',
  'auth.register.title': 'Crea tu cuenta',
  'auth.register.subtitle': 'Solicita acceso a TransitOps Control Panel.',
  'auth.register.personalInfo': 'Información personal',
  'auth.register.accountAccess': 'Acceso de cuenta',
  'auth.register.verification': 'Verificación',
  'auth.register.requestedRole': 'Rol solicitado',
  'auth.register.firstName': 'Nombre',
  'auth.register.lastName': 'Apellido',
  'auth.register.phone': 'Teléfono',
  'auth.register.confirmPassword': 'Confirmar contraseña',
  'auth.register.emailCode': 'Código de correo',
  'auth.register.phoneCode': 'Código de teléfono',
  'auth.register.sendEmailCode': 'Enviar código de correo',
  'auth.register.sendingEmailCode': 'Enviando código de correo...',
  'auth.register.sendPhoneCode': 'Enviar código de teléfono',
  'auth.register.sendingPhoneCode': 'Enviando código de teléfono...',
  'auth.register.mockCodesNote':
    'Códigos mock solo para desarrollo: correo 123456 y teléfono 654321.',
  'auth.register.roleLabel': 'Selecciona el nivel de acceso a solicitar',
  'auth.register.roleViewer': 'Consulta',
  'auth.register.roleOperator': 'Operador',
  'auth.register.roleSupervisor': 'Supervisor',
  'auth.register.registerAccount': 'Registrar cuenta',
  'auth.register.registering': 'Registrando cuenta...',
  'auth.register.haveAccount': '¿Ya tienes cuenta?',
  'auth.register.signIn': 'Iniciar sesión',
  'auth.register.successTitle': 'Registro exitoso',
  'auth.register.successMessage':
    'Tu cuenta fue creada con el rol solicitado. Ahora puedes volver al login.',
  'auth.register.successActiveMessage':
    'Tu cuenta de consulta está activa. Ahora puedes iniciar sesión.',
  'auth.register.successPendingMessage':
    'Tu cuenta fue creada y queda pendiente de aprobación administrativa antes de iniciar sesión.',
  'auth.register.goToLogin': 'Ir al login',
  'auth.register.emailCodeSent': 'Código de correo enviado. Usa el código mock 123456.',
  'auth.register.phoneCodeSent': 'Código de teléfono enviado. Usa el código mock 654321.',
  'auth.register.emailCodeError': 'No se pudo enviar el código de correo. Inténtalo de nuevo.',
  'auth.register.phoneCodeError': 'No se pudo enviar el código de teléfono. Inténtalo de nuevo.',
  'auth.register.error': 'No se pudo registrar la cuenta. Inténtalo de nuevo.',
  'auth.validation.emailRequired': 'El correo es obligatorio.',
  'auth.validation.emailValid': 'Ingresa un correo válido.',
  'auth.validation.passwordRequired': 'La contraseña es obligatoria.',
  'auth.validation.firstNameRequired': 'El nombre es obligatorio.',
  'auth.validation.lastNameRequired': 'El apellido es obligatorio.',
  'auth.validation.phoneRequired': 'El teléfono es obligatorio.',
  'auth.validation.phoneValid': 'Ingresa un número de teléfono válido.',
  'auth.validation.emailCodeRequired': 'El código de correo es obligatorio.',
  'auth.validation.phoneCodeRequired': 'El código de teléfono es obligatorio.',
  'auth.validation.passwordMinLength': 'La contraseña debe tener al menos 8 caracteres.',
  'auth.validation.confirmPasswordRequired': 'Confirmar la contraseña es obligatorio.',
  'auth.validation.passwordMatch': 'Las contraseñas deben coincidir.',
  'auth.validation.requestedRoleRequired': 'El rol solicitado es obligatorio.',
  'auth.accessDenied.title': 'Acceso denegado',
  'auth.accessDenied.message': 'No tienes permiso para acceder a este recurso.',
  'status.available': 'Disponible',
  'status.maintenance': 'Mantenimiento',
  'status.inactive': 'Inactivo',
  'status.active': 'Activo',
  'status.pendingApproval': 'Pendiente de aprobación',
  'status.rejected': 'Rechazado',
  'status.suspended': 'Suspendido',
  'status.scheduled': 'Programado',
  'status.inProgress': 'En curso',
  'status.completed': 'Completado',
  'status.cancelled': 'Cancelado',
};

export const languageTranslations = {
  en: enTranslations,
  es: esTranslations,
} as const;

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  private readonly platformId = inject(PLATFORM_ID);
  private readonly isBrowser = isPlatformBrowser(this.platformId);
  private readonly languageKey = 'transitops_language';

  private readonly currentLanguageSubject = new BehaviorSubject<AppLanguage>(
    this.getInitialLanguage(),
  );

  readonly currentLanguage$ = this.currentLanguageSubject.asObservable();
  readonly supportedLanguages: readonly AppLanguage[] = ['en', 'es'];

  constructor() {
    this.applyLanguage(this.currentLanguageSubject.value);
  }

  getCurrentLanguage(): AppLanguage {
    return this.currentLanguageSubject.value;
  }

  setLanguage(language: AppLanguage): void {
    if (this.isBrowser) {
      localStorage.setItem(this.languageKey, language);
    }

    this.currentLanguageSubject.next(language);
    this.applyLanguage(language);
  }

  translate(key: TranslationKey): string {
    return languageTranslations[this.currentLanguageSubject.value][key];
  }

  private getInitialLanguage(): AppLanguage {
    if (!this.isBrowser) {
      return 'en';
    }

    const storedLanguage = localStorage.getItem(this.languageKey);

    if (this.isSupportedLanguage(storedLanguage)) {
      return storedLanguage;
    }

    return 'en';
  }

  private isSupportedLanguage(language: string | null): language is AppLanguage {
    return language === 'en' || language === 'es';
  }

  private applyLanguage(language: AppLanguage): void {
    this.document.documentElement.setAttribute('lang', language);
  }
}
